default_stages: [commit, push, manual]
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-encoding-pragma
      - id: check-docstring-first
      - id: flake8
        args: ["--max-line-length=100"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        types: [text]
